// flow-typed signature: 41ae7852e12f31cf63d47dc219594283
// flow-typed version: <<STUB>>/ansi-styles_v4.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ansi-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ansi-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ansi-styles/index' {
  declare module.exports: $Exports<'ansi-styles'>;
}
declare module 'ansi-styles/index.js' {
  declare module.exports: $Exports<'ansi-styles'>;
}
