// flow-typed signature: 7d4a27f8696ab37b9908b9b2d73fff6e
// flow-typed version: <<STUB>>/ansi-styles_v3.2.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ansi-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ansi-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ansi-styles/index' {
  declare module.exports: $Exports<'ansi-styles'>;
}
declare module 'ansi-styles/index.js' {
  declare module.exports: $Exports<'ansi-styles'>;
}
