// flow-typed signature: 2587e8f828308871fe6bb6dc98221b7b
// flow-typed version: <<STUB>>/babel-preset-playlyfe_v3.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-playlyfe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-playlyfe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-playlyfe/lib/index' {
  declare module.exports: any;
}

declare module 'babel-preset-playlyfe/lib/plugins/react-intl' {
  declare module.exports: any;
}

declare module 'babel-preset-playlyfe/lib/presets/es' {
  declare module.exports: any;
}

declare module 'babel-preset-playlyfe/lib/presets/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-playlyfe/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-playlyfe/lib/index'>;
}
declare module 'babel-preset-playlyfe/lib/plugins/react-intl.js' {
  declare module.exports: $Exports<'babel-preset-playlyfe/lib/plugins/react-intl'>;
}
declare module 'babel-preset-playlyfe/lib/presets/es.js' {
  declare module.exports: $Exports<'babel-preset-playlyfe/lib/presets/es'>;
}
declare module 'babel-preset-playlyfe/lib/presets/react.js' {
  declare module.exports: $Exports<'babel-preset-playlyfe/lib/presets/react'>;
}
