// flow-typed signature: b178252d1734b51dfa0f791bb1722202
// flow-typed version: <<STUB>>/cacache_v11.3.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cacache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cacache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cacache/en' {
  declare module.exports: any;
}

declare module 'cacache/es' {
  declare module.exports: any;
}

declare module 'cacache/get' {
  declare module.exports: any;
}

declare module 'cacache/lib/content/path' {
  declare module.exports: any;
}

declare module 'cacache/lib/content/read' {
  declare module.exports: any;
}

declare module 'cacache/lib/content/rm' {
  declare module.exports: any;
}

declare module 'cacache/lib/content/write' {
  declare module.exports: any;
}

declare module 'cacache/lib/entry-index' {
  declare module.exports: any;
}

declare module 'cacache/lib/memoization' {
  declare module.exports: any;
}

declare module 'cacache/lib/util/fix-owner' {
  declare module.exports: any;
}

declare module 'cacache/lib/util/hash-to-segments' {
  declare module.exports: any;
}

declare module 'cacache/lib/util/move-file' {
  declare module.exports: any;
}

declare module 'cacache/lib/util/tmp' {
  declare module.exports: any;
}

declare module 'cacache/lib/util/y' {
  declare module.exports: any;
}

declare module 'cacache/lib/verify' {
  declare module.exports: any;
}

declare module 'cacache/locales/en' {
  declare module.exports: any;
}

declare module 'cacache/locales/es' {
  declare module.exports: any;
}

declare module 'cacache/ls' {
  declare module.exports: any;
}

declare module 'cacache/put' {
  declare module.exports: any;
}

declare module 'cacache/rm' {
  declare module.exports: any;
}

declare module 'cacache/verify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cacache/en.js' {
  declare module.exports: $Exports<'cacache/en'>;
}
declare module 'cacache/es.js' {
  declare module.exports: $Exports<'cacache/es'>;
}
declare module 'cacache/get.js' {
  declare module.exports: $Exports<'cacache/get'>;
}
declare module 'cacache/index' {
  declare module.exports: $Exports<'cacache'>;
}
declare module 'cacache/index.js' {
  declare module.exports: $Exports<'cacache'>;
}
declare module 'cacache/lib/content/path.js' {
  declare module.exports: $Exports<'cacache/lib/content/path'>;
}
declare module 'cacache/lib/content/read.js' {
  declare module.exports: $Exports<'cacache/lib/content/read'>;
}
declare module 'cacache/lib/content/rm.js' {
  declare module.exports: $Exports<'cacache/lib/content/rm'>;
}
declare module 'cacache/lib/content/write.js' {
  declare module.exports: $Exports<'cacache/lib/content/write'>;
}
declare module 'cacache/lib/entry-index.js' {
  declare module.exports: $Exports<'cacache/lib/entry-index'>;
}
declare module 'cacache/lib/memoization.js' {
  declare module.exports: $Exports<'cacache/lib/memoization'>;
}
declare module 'cacache/lib/util/fix-owner.js' {
  declare module.exports: $Exports<'cacache/lib/util/fix-owner'>;
}
declare module 'cacache/lib/util/hash-to-segments.js' {
  declare module.exports: $Exports<'cacache/lib/util/hash-to-segments'>;
}
declare module 'cacache/lib/util/move-file.js' {
  declare module.exports: $Exports<'cacache/lib/util/move-file'>;
}
declare module 'cacache/lib/util/tmp.js' {
  declare module.exports: $Exports<'cacache/lib/util/tmp'>;
}
declare module 'cacache/lib/util/y.js' {
  declare module.exports: $Exports<'cacache/lib/util/y'>;
}
declare module 'cacache/lib/verify.js' {
  declare module.exports: $Exports<'cacache/lib/verify'>;
}
declare module 'cacache/locales/en.js' {
  declare module.exports: $Exports<'cacache/locales/en'>;
}
declare module 'cacache/locales/es.js' {
  declare module.exports: $Exports<'cacache/locales/es'>;
}
declare module 'cacache/ls.js' {
  declare module.exports: $Exports<'cacache/ls'>;
}
declare module 'cacache/put.js' {
  declare module.exports: $Exports<'cacache/put'>;
}
declare module 'cacache/rm.js' {
  declare module.exports: $Exports<'cacache/rm'>;
}
declare module 'cacache/verify.js' {
  declare module.exports: $Exports<'cacache/verify'>;
}
