// flow-typed signature: dd05e6e196a6b3847d7e60dcf277ce43
// flow-typed version: <<STUB>>/resolve-from_v5.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resolve-from'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resolve-from' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'resolve-from/index' {
  declare module.exports: $Exports<'resolve-from'>;
}
declare module 'resolve-from/index.js' {
  declare module.exports: $Exports<'resolve-from'>;
}
