// flow-typed signature: 01d8e7e2ce8960becd7032726b2bf851
// flow-typed version: <<STUB>>/rev-hash_v2.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rev-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rev-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rev-hash/index' {
  declare module.exports: $Exports<'rev-hash'>;
}
declare module 'rev-hash/index.js' {
  declare module.exports: $Exports<'rev-hash'>;
}
